import type { EnCatalog } from './en';

/** Japanese UI overlay. Falls back to English for missing keys. */
export const ja: DeepPartial<EnCatalog> = {
    downloads: { page: { eyebrow: 'ダウンロード', title: 'ダウンロード状況', description: 'Sonarr、Radarr、Lidarrごとに設定されたダウンロードクライアントを表示します。' }, actions: { refresh: '更新', clearClientFilter: 'クライアントのフィルターを解除', pause: '一時停止', resume: '再開', remove: '削除' }, filters: { client: 'クライアント', show: '表示', activeOnly: 'アクティブのみ', all: 'すべて', allClients: 'すべてのクライアント', other: 'その他', shown: '{count}件を表示', hidingCompleted: '完了済み/シード中を非表示' }, labels: { clients: 'クライアント', downloadClient: 'ダウンロードクライアント', downloadCount: '{count}件のダウンロード', downloadCount_plural: '{count}件のダウンロード', downSpeed: '下り {value}/s', upSpeed: '上り {value}/s', matchedFromArrQueue: 'Arrキューに一致' }, status: { activeDownloads: 'アクティブなダウンロード', downloads: 'ダウンロード', unknown: '不明' }, empty: { noClients: '設定にダウンロードクライアントがありません。', noFilterResults: 'このフィルターに該当するダウンロードはありません。' }, upload: { title: 'Torrentを追加', subtitle: '設定済みクライアントにURL、マグネット、ファイルを送信', client: 'クライアント', category: 'カテゴリ', torrentUrl: 'Torrent URLまたはマグネット', torrentFile: 'Torrentファイル', noCategory: 'カテゴリなし', sending: '送信中…', add: 'Torrentを追加' }, errors: { loadFailed: 'ダウンロードを読み込めませんでした', actionFailed: 'ダウンロードを{action}できませんでした', chooseClient: '先にダウンロードクライアントを選択してください。', missingSource: 'Torrent URL、マグネットリンク、またはTorrentファイルを追加してください。', addFailed: 'Torrentを追加できませんでした' }, confirm: { remove: '「{name}」を{client}から削除しますか？クライアントが対応している場合、ダウンロード済みファイルは残ります。' } },
    calendar: {
        page: { tvDescription: 'メディアスタック全体のTVシリーズの配信、ダウンロード、アクティビティ。', movieDescription: 'メディアスタック全体の映画の配信、ダウンロード、アクティビティ。' },
        actions: { refresh: '更新', configureInSettings: '設定で構成 →' },
        sections: { upcomingReleases: '近日公開', downloads: '{name}のダウンロード', history: '{name}の履歴', status: '{name}のステータス' },
        relative: { today: '今日', tomorrow: '明日', atTime: ' {time}', nextMonthNotice: '{type}の公開がある次の月を表示しています（{month}）。', noNextReleases: '今後6か月間に{type}の公開はありません。' },
        status: { unconfigured: '未設定', online: 'オンライン', ready: '準備完了', monitored: '監視中', freeStorage: '空き容量', freeGb: '{value} GB 空き', usedPercent: '{value}% 使用済み', totalGb: '合計 {value} GB' },
        labels: { requestedNotAired: 'リクエスト済み — まだ放送されていません', requestedNotReleased: 'リクエスト済み — まだ公開されていません', unableToFetch: '{name}からデータを取得できません。URL、APIキー、ローカルネットワークを確認してください。', subtitleAutomation: '字幕の管理と自動化', musicAutomation: '音楽ライブラリの自動化', active: '{count}件がアクティブ' },
        empty: { notConfigured: '{name}はまだ設定されていません。', configurationHint: '設定 → インテグレーションでURLとAPIキーを追加してください。', noUpcoming: '今月公開予定の{type}はありません', noPoster: 'ポスターなし', noActiveDownloads: 'アクティブな{type}のダウンロードはありません', noRecentHistory: '最近の{type}の履歴はありません', unknownTime: '時刻不明' },
        fallback: { unknownSeries: '不明なシリーズ', unknownTvShow: '不明なTV番組', unknownMovie: '不明な映画', movieRelease: '映画公開' },
        events: { grabbed: '取得済み', imported: 'インポート済み', failed: '失敗', deleted: '削除済み' },
        errors: { loadFailed: 'メディアスタックのデータを読み込めませんでした。' },
    },
};

Object.assign(ja, { statusPage: { page: { eyebrow: 'システムステータス', title: 'サーバーステータス', description: 'サービスの可用性とパフォーマンスを監視します。' }, actions: { back: '戻る', refresh: '更新' }, tabs: { overview: '概要', history: '履歴', analytics: '分析' }, summary: { online: '{total} 件中 {online} 件がオンライン', offline: '{count} 件がオフライン', fleetUptime: '{period} の稼働率: {value}%' }, labels: { section: 'ステータス', services: 'サービス', ungrouped: '未分類', periodUptime: '{period} の稼働率', groupSummary: '{count} サービス · {period} の稼働率', uptimeValue: '{period} の稼働率: {value}%', latencyValue: 'レイテンシ: {value}', average: '(平均 {value})', adminOnly: '管理者のみ', adminOnlyHint: '管理者にのみ表示' }, status: { online: 'オンライン', degraded: '低下', offline: 'オフライン', unknown: '不明', healthy: '正常', outage: '停止' }, empty: { noServicesTitle: 'ステータスサービスが設定されていません', noServicesSubtitle: 'ステータスサービスはまだ設定されていません。', blank: 'サービスを設定するとステータスが表示されます。', adminHint: '管理者はステータスモニター設定から設定できます。', memberHint: '管理者にステータスサービスの設定を依頼してください。', noHistory: '履歴データはありません。', noIncidents: 'この期間にインシデントはありません。', noData: 'データなし', latencyHistory: 'レイテンシ履歴データはありません。' }, relative: { hoursAgo: '{count} 時間前', daysAgo: '{count} 日前', periodAgo: '{period} 前', now: '現在' }, history: { subtitle: '過去 {period} の履歴とインシデント', hourUtc: '時刻 (UTC)', date: '日付', uptimePercent: '稼働率', checks: 'チェック', averageLatency: '平均レイテンシ', status: 'ステータス' }, incidents: { title: 'インシデント · {period}', started: '開始', ended: '終了', duration: '期間', severity: '重大度', ongoing: '進行中' }, analytics: { uptime: '稼働率', checks: 'チェック', averageLatency: '平均レイテンシ', p95Latency: 'P95 レイテンシ', incidents: 'インシデント', longestOutage: '最長停止', healthyStreak: '正常継続', worstDay: '最悪の日', uptimeTrend: '稼働率 · {name}', rollingUptime: '{period} の推移', latencyTitle: 'レイテンシ · {name}', averageResponseTime: '{period} の平均応答時間', best: '最良の日: {value} · {pct}%', worst: '最悪の日: {value} · {pct}%' }, errors: { loadFailed: 'ステータスデータを読み込めませんでした。' }, speedTest: { title: '接続テスト', description: 'ブラウザとポータル間のレイテンシと帯域幅を測定します。', run: 'テストを実行', runAgain: '再テスト', measuringLatency: 'レイテンシを測定中…', testingDownload: 'ダウンロードをテスト中…', testingUpload: 'アップロードをテスト中…', ready: '準備完了', complete: 'テスト完了', failed: 'テスト失敗', error: '接続テストに失敗しました', latency: 'レイテンシ', download: 'ダウンロード', upload: 'アップロード', roundTrip: '往復時間', downloadHint: '推定ダウンロード速度', uploadHint: '推定アップロード速度', highLatencyHint: '高いレイテンシはネットワークの混雑や距離が原因の可能性があります。', steadyStateHint: '結果は現在の接続を反映し、変動する場合があります。', progress: '実行中…' } } });

type DeepPartial<T> = {
    [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};
