import requests
from configparser import ConfigParser

def get_Language(movie_data, excluded_languages, skip_multiple_audio_tracks):
    language_mapping = {
        'Afrikaans': 'Afrikaans',
        'Akan': 'Akan',
        'Shqip': 'Albanian',
        'አማርኛ': 'Amharic',
        'العربية': 'Arabic',
        'Aragonés': 'Aragonese',
        'հայերեն': 'Armenian',
        'অসমীয়া': 'Assamese',
        'Asturianu': 'Asturian',
        'Azərbaycan': 'Azerbaijani',
        'Башҡортса': 'Bashkir',
        'Euskara': 'Basque',
        'Беларуская': 'Belarusian',
        'বাংলা': 'Bengali',
        'Bosanski': 'Bosnian',
        'Brezhoneg': 'Breton',
        'Български': 'Bulgarian',
        'ဗမာစာ': 'Burmese',
        'Català': 'Catalan',
        'Cebuano': 'Cebuano',
        'ᏣᎳᎩ': 'Cherokee',
        '中文': 'Chinese',
        '广东话': 'Cantonese',
        '普通话': 'Mandarin',
        'Corsu': 'Corsican',
        'Hrvatski': 'Croatian',
        'Čeština': 'Czech',
        'Dansk': 'Danish',
        'ދިވެހި': 'Dhivehi',
        'Nederlands': 'Dutch',
        'ཇོང་ཁ': 'Dzongkha',
        'English': 'English',
        'Esperanto': 'Esperanto',
        'Eesti': 'Estonian',
        'Føroyskt': 'Faroese',
        'Fiji Hindi': 'Fiji Hindi',
        'Filipino': 'Filipino',
        'Suomi': 'Finnish',
        'Français': 'French',
        'Frysk': 'Frisian',
        'Fulfulde': 'Fulah',
        'Galego': 'Galician',
        'ქართული': 'Georgian',
        'Deutsch': 'German',
        'Ελληνικά': 'Greek',
        'Kalaallisut': 'Greenlandic',
        'ગુજરાતી': 'Gujarati',
        'Kreyòl ayisyen': 'Haitian Creole',
        'Hausa': 'Hausa',
        'ʻŌlelo Hawaiʻi': 'Hawaiian',
        'עברית': 'Hebrew',
        'हिन्दी': 'Hindi',
        'Hmong': 'Hmong',
        'Hungarian': 'Hungarian',
        'Magyar': 'Hungarian',
        'Íslenska': 'Icelandic',
        'Igbo': 'Igbo',
        'Ilokano': 'Ilokano',
        'Bahasa Indonesia': 'Indonesian',
        'Gaeilge': 'Irish',
        'Italiano': 'Italian',
        '日本語': 'Japanese',
        'Basa Jawa': 'Javanese',
        'ಕನ್ನಡ': 'Kannada',
        'Қазақ тілі': 'Kazakh',
        'ភាសាខ្មែរ': 'Khmer',
        'Kinyarwanda': 'Kinyarwanda',
        'Kiswahili': 'Swahili',
        '한국어': 'Korean',
        'Kurdî': 'Kurdish',
        'Кыргызча': 'Kyrgyz',
        'ລາວ': 'Lao',
        'Latviešu': 'Latvian',
        'Lietuvių': 'Lithuanian',
        'Lëtzebuergesch': 'Luxembourgish',
        'Македонски': 'Macedonian',
        'Malagasy': 'Malagasy',
        'Bahasa Melayu': 'Malay',
        'മലയാളം': 'Malayalam',
        'Malti': 'Maltese',
        'Māori': 'Maori',
        'मराठी': 'Marathi',
        'Монгол': 'Mongolian',
        'myn': 'Mayan',
        "Mayaq'ik": 'Mayan',
        'magyar': 'Hungarian',
        'नेपाली': 'Nepali',
        'Norsk': 'Norwegian',
        'norsk': 'Norwegian',
        'Occitan': 'Occitan',
        'ଓଡ଼ିଆ': 'Odia',
        'Afaan Oromoo': 'Oromo',
        'پښتو': 'Pashto',
        'فارسی': 'Persian',
        'Polski': 'Polish',
        'Português': 'Portuguese',
        'ਪੰਜਾਬੀ': 'Punjabi',
        'Quechua': 'Quechua',
        'Română': 'Romanian',
        'Rumantsch': 'Romansh',
        'Русский': 'Russian',
        'Samoan': 'Samoan',
        'Sängö': 'Sango',
        'Gaelic': 'Scottish Gaelic',
        'Српски': 'Serbian',
        'Sesotho': 'Sesotho',
        'Setswana': 'Setswana',
        'Shona': 'Shona',
        'සිංහල': 'Sinhala',
        'Slovenčina': 'Slovak',
        'Slovenščina': 'Slovenian',
        'Soomaaliga': 'Somali',
        'Español': 'Spanish',
        'Basa Sunda': 'Sundanese',
        'Svenska': 'Swedish',
        'Tagalog': 'Tagalog',
        'தமிழ்': 'Tamil',
        'Татарча': 'Tatar',
        'తెలుగు': 'Telugu',
        'ไทย': 'Thai',
        'བོད་ཡིག': 'Tibetan',
        'Tigrinya': 'Tigrinya',
        'Türkçe': 'Turkish',
        'Türkmen': 'Turkmen',
        'Українська': 'Ukrainian',
        'اردو': 'Urdu',
        'Uyghur': 'Uyghur',
        'Tiếng Việt': 'Vietnamese',
        'Cymraeg': 'Welsh',
        'Wolof': 'Wolof',
        'isiXhosa': 'Xhosa',
        'ייִדיש': 'Yiddish',
        'Yorùbá': 'Yoruba',
        'isiZulu': 'Zulu'
    }

    audio_tracks = []

    for media in movie_data.get('Media', []):
        for part in media.get('Part', []):
            for stream in part.get('Stream', []):
                if stream.get('streamType') == 2:
                    lang_raw = stream.get('language')
                    if lang_raw:
                        audio_tracks.append(lang_raw)

    # If there are multiple audio tracks and config says skip
    if len(audio_tracks) > 1 and skip_multiple_audio_tracks:
        return None

    for lang in audio_tracks:
        norm = language_mapping.get(lang, lang)
        if norm not in ['Unknown', 'Undetermined', 'Undetermined language'] and norm not in excluded_languages:
            return norm

    return None
